# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b4491153ae953f15b542c27d49f84b2"
name = "trust-support"
handle = "trust-support"
application_url = "https://observations-crossing-lets-dsc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gwa-checkout-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://observations-crossing-lets-dsc.trycloudflare.com/auth/callback",
  "https://observations-crossing-lets-dsc.trycloudflare.com/auth/shopify/callback",
  "https://observations-crossing-lets-dsc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
