# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-01"

[[extensions]]
type = "ui_extension"
name = "trust-icons"
handle = "trust-icons"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "block_title1"
type = "single_line_text_field"
name = "Block title1"
description = "Enter a title for the first block"

[[extensions.settings.fields]]
key = "block_subtitle1"
type = "single_line_text_field"
name = "Block subtitle1"
description = "Enter a subtitle for the first block"

[[extensions.settings.fields]]
key = "image_url1"
type = "single_line_text_field"
name = "Image Url1"
description = "Image Url for the first block"

[[extensions.settings.fields]]
key = "block_title2"
type = "single_line_text_field"
name = "Block title2"
description = "Enter a title for the second block"

[[extensions.settings.fields]]
key = "block_subtitle2"
type = "single_line_text_field"
name = "Block subtitle2"
description = "Enter a subtitle for the second block"

[[extensions.settings.fields]]
key = "image_url2"
type = "single_line_text_field"
name = "Image Url2"
description = "Image Url for the second block"